name: Build and Deploy

on:
  push:
    branches: [ "react-main" ]
  pull_request:
    branches: [ "react-main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: |
          npm i
          npm run build
          npm run deploy
