name: Fetch Data

on:
  schedule:
    # Runs "At minute 0 past every 4th hour." (see https://crontab.guru)
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Build Project
        run: |
          npm i
          npm run update-data
          npm run build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
