name: Fetch Data

on:
  schedule:
    # Runs "At minute 0 past every 4th hour." (see https://crontab.guru)
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Update Data
        run: |
          npm i
          npm run update-data
      - name: Commit and push changes
        run: |
          git config --global user.name "jhasuraj01"
          git config --global user.email "44930179+jhasuraj01@users.noreply.github.com"
          git add -A
          git commit -m "Updated Data"
          git push